version: '3.8'

services:
  sprint1:
    image: sprint1:latest
    build:
      context: .
      dockerfile: Sprint1/Dockerfile
    ports:
      - "8081:8081"    # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
    restart: unless-stopped
